/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.logging.log4j.core.impl.Log4jLogEvent;

public class App {
    public String getGreeting() {
        @SuppressWarnings("unused")
        var logEvent = new Log4jLogEvent();
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
